### ISSUE TITLE
created/updated times for a dandiset record, what are they really?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-publish#107]
Looking at
```
$> curl --silent -X GET "http://publish.dandiarchive.org/api/dandisets/000006/versions/0.200714.1807/" -H "accept: application/json" | jq . | head -n 10
{
  "dandiset": {
    "identifier": "000006",
    "created": "2020-07-14T18:07:58.698604Z",
    "updated": "2020-07-14T18:07:58.698622Z"
  },
  "version": "0.200714.1807",
  "created": "2020-07-14T18:07:59.179296Z",
  "updated": "2020-07-14T18:07:59.179341Z",
  "count": 53,
```
I see two values for created and updated which differ (only) slightly.  What do they really correspond to? 

My wild guess would have been that `dandiset.` times would correspond to the entire dandiset, not this specific version, and then top level created would be for when versioned release created.

But 
- I do not quite comprehend what (different) "updated" would mean for a released version since it should be the same time (but technically could be when "release" has finished doing its thing?)
- according to https://gui.dandiarchive.org/#/dandiset/5e70d0fe3da50caa9adaf2d7 00006  was created in march not in 2020-07-14, so my wild guess is also off. 
- if `dandiset.` is for the entire dandiset, I then I would expect `dandiset.updated` to be the `latest()` of all other dates, but that is not what it is either.

So what are those date times?

**Comment by mgrauer** [comment]
Good questions!

We have issues open because we need to determine policies for both of these.

#32, #33.

**Comment by yarikoptic** [comment]
FWIW, why I care ATM, is that I use `modified` (well, mtime from girder) to set mtime for `dandiset.yaml` which I produce from the metadata for the dandiset. So I could, like for any other file, say "did not change" if mtime is the same

**Comment by brianhelba** [comment]
#142 should ensure that the `modified` field (renamed from `updated`) will now be bumped upon any change to the underlying database data. It is possible that for a freshly-created entity, `modified` could be several milliseconds before `created`, but that's just an artifact of internal application timing, and will eventually go away as further updates to the entity bump the `modified` time.

If you discover any circumstances under which `modified` is not getting bumped in response to data changes, please file a new issue.
