### ISSUE TITLE
why asset's "path"  is absolute (i.e. starts with `/`)?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-publish#109]
I.e. - is that leading `/` provides any additional information?  Could API return a path without leading `/`?

if answer is "no" to both --  could it may be stripped?  I guess the reason is to "simplify" paths operations so clients could just concatenate path strings.  But IMHO that is a suboptimal practice, and paths should be operated using helper functions instead of adhoc strings concatenation.

That would simplify using that relative (as to the top of the dandiset) path for manipulation, since e.g. in python providing "absolute" path to `os.path.join`:
```
(Pdb) os.path.join('00001', '/my/subpath')
'/my/subpath'
```
and thus any client would need to strip it away when manipulating paths "properly"

**Comment by AlmightyYakob** [comment]
What's wrong with stripping leading slashes on the client?

**Comment by yarikoptic** [comment]
hm... sure clients could do all kinds of pre-processing... let's may be add `%` at the beginning as well - clients could strip it off as well.
an alternative counter-question: what is "right" about clients needing to convert "wrong" absolute paths into relative ones to use them?

**Comment by dchiquit** [comment]
Conceptually, that path is "absolute" for a given dandiset+version. I agree that's a weird thing to be absolute to. Under the hood we use `path=girder_file.path` to assign it, so I assume this implementation was simply the path of least resistance.
I think either making this path relative (`my/subpath`) or making it really absolute (`/000001/0.200714.1807/my/subpath`) would be better.
@brianhelba any design thoughts?

**Comment by yarikoptic** [comment]
I think it is better to not prepend dataset identifier (`/000001`). Rationale: dandiset could be versioned or not.  Users might want to install one version into one directory (e.g. 000001), and another in another (e.g. versioned release into `000001-v1`).  Not ATM but eventually we might RF dandi-cli download so that output directory would be the top of the dandiset (ATM it would create dandiset directory UNDER the output path specified).  Started https://github.com/dandi/dandi-cli/issues/140 .
FWIW, in my RFing of dandi-cli to support new API I already needed to strip off such identifier from file paths provided by girder (since those paths relative to the top of drafts collection), although I largely do it to "harmonize" with the PATH returned by API.

**Comment by mgrauer** [comment]
This path (maybe the naming isn't great) is intended to be a path in an abstract dandiset space, it's not intended to map onto a filesystem (from the perspective of the server/API). I'll go ahead and close this one.

**Comment by yarikoptic** [comment]
There is nothing "abstract" about it to my taste, and does not explain what benefit you get from having it "absolute" in some "abstract" space but that is ok, I can workaround.
