### ISSUE TITLE
drf-extensions is incompatible with latest version of Django

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-publish#119]
My current attempts to run this code (as part of dandi/dandi-cli#164) are failing with the following error (traceback truncated):

```
  File "/usr/local/lib/python3.8/site-packages/rest_framework_extensions/key_constructor/bits.py", line 3, in <module>
    from django.db.models.sql.datastructures import EmptyResultSet
ImportError: cannot import name 'EmptyResultSet' from 'django.db.models.sql.datastructures' (/usr/local/lib/python3.8/site-packages/django/db/models/sql/datastructures.py)
```

It seems this is due to drf-extensions being incompatible with Django 3.1.   drf-extensions [has a fix for this](https://github.com/chibisov/drf-extensions/commit/8001a440c7322be26bbe2d16f3a334a8b0b5860b) but has not yet released it.  Until drf-extensions releases a new version, it would probably be a good idea to restrict this project's django requirement to `<3.1` or stricter.

**Comment by mgrauer** [comment]
Fixed by #124 .
