### ISSUE TITLE
Getting auth token programmatically?

### ISSUE THREAD

**Issue by jwodder** [dandi/dandi-publish#121]
For dandi/dandi-cli#164, I need a way to get an auth token from the dandi-publish Django instance using the API instead of the GUI.  Is there an API route that supports this?  [This page](https://simpleisbetterthancomplex.com/tutorial/2018/11/22/how-to-implement-token-authentication-using-django-rest-framework.html#user-requesting-a-token) suggests that such a route is not automatic and must be implemented explicitly.

**Comment by mgrauer** [comment]
For now this is a manual process, just to bridge across to Girder from publish, but this should be a one time setup.

**Comment by brianhelba** [comment]
Agreed, the need for this should eventually be phased out, so I don't think it's worth the investment to add a temporary API for it.
