### ISSUE TITLE
Introduce CI testing run against released dandi-cli

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-publish#145]
Similar to what was done for `redirector` in https://github.com/dandi/redirector/pull/33/files .

I believe that recent changes might have broke dandi-cli download since I am getting:

```
=================================================== FAILURES ====================================================
_________________ test_download_000027[https://dandiarchive.org/dandiset/000027/0.200721.2222] __________________
dandi/tests/test_download.py:197: in test_download_000027
    ret = download(url, tmpdir)
dandi/download.py:322: in download
    for rec in gen_:
dandi/download.py:471: in download_generator
    for resp in _download_generator:
dandi/download.py:801: in _download_file
    os.utime(path, (time.time(), mtime.timestamp()))
E   AttributeError: 'str' object has no attribute 'timestamp'

```
on its current master (0.6.2-57-g00414f5) and 0.6.2 .  I am yet to investigate and either fix dandi-cli or see some fix in `dandi-publish`.

In general -- no changes in API which might break client should be "deployed" until client is ready to handle them. Such CI run should help to ensure that.

**Comment by brianhelba** [comment]
I think integration testing between the publish app and the client is a great idea eventually, but until we have a unified API, I suspect the engineering effort may not be worthwhile now, and it may continually break as the integration between the `dandiarchive` and `dandi-publish` codebases continues to evolve.

The more basic issue here is to define a supported API surface explicitly. We have a lot of work to do to reach a unified API, and further incompatible changes will likely be necessary.

Which particular endpoints of the publish app does the client depend on presently?

In a nearer term, if we define and agree on some public API surface, we can ensure we have direct tests and a change notification process for those endpoints.

**Comment by yarikoptic** [comment]
@brianhelba -- dandi-cli is **already** using API to provide downloads of released versions of datasests which are **coming very soon**.  We **already** have users using dandi cli to upload datasets, and dandi client **already** uses locking functionality...

> Which particular endpoints of the publish app does the client depend on presently?

not that many. have a pick at https://github.com/dandi/dandi-cli/blob/master/dandi/dandiapi.py#L209 .

> In a nearer term, if we define and agree on some public API surface, we can ensure we have direct tests and a change notification process for those endpoints.

So far I have largely agreed with what you came up for the API, and started to use it while issuing issues for your consideration.  I can agree again if it would be helpful ;-)  Looking forward, I can also account for changes in the API rather easily and force users to install newer dandi-cli now, BUT API changes should not get deployed **before** that newer dandi-cli gets released.  That is why possibly moving dandi-publish into deployment from tags instead of master might be preferable.

**Comment by yarikoptic** [comment]
well, dandi-publish "is no more" AFAIK and similar action was done in its replacement - dandi-api: https://github.com/dandi/dandi-api/blob/master/.github/workflows/cli-integration.yml  so we can close this one
