### ISSUE TITLE
Please tag some version(s)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-publish#146]
Ideally there could be 0.1.0 tag for a version a few days back before it broke dandi-cli (see #145 and https://github.com/dandi/dandi-cli/issues/228).  Then it would make it easier (in the future, after we figure out how to establish a working docker-compose setup with dandi-publish, see https://github.com/dandi/dandi-cli/issues/164 and issues referenced there in) to be able to re-validate correct operation of `dandi-cli` against released version of dandi-publish (API) simply by going back to a docker image(s) built for that version.

**Comment by brianhelba** [comment]
Let's fold this into #80 please, to avoid issue sprawl.
