### ISSUE TITLE
/publish/ API endpoint should not require client's interactions with girder and `/sync` first.

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-publish#149]
according to https://github.com/dandi/dandi-cli/pull/189#issuecomment-689545589 and interactions on slack `/dandisets/{dandiset__pk}/versions/publish/` requires girder folder ID for dandiset, `/sync/` call prior etc.

None of that should be necessary AFAIK.  `dandi-publish` (API) implementation should perform internally all necessary interactions with archive backend (girder) to e.g. figure out girder folder id for the current draft of `{dandiset__pk}` and if needed to invoke any `/sync/` functionality it needs.

**Comment by mgrauer** [comment]
I agree, this is on the roadmap to a unified API, removing the interaction with Girder in the publish service.

See https://github.com/dandi/dandi-publish/pull/46 and https://github.com/dandi/dandiarchive/pull/402 for some history.
