### ISSUE TITLE
Support API key auth

### ISSUE THREAD

**Issue by brianhelba** [dandi/dandi-publish#16]
This may be best handled by OAuth2: https://django-oauth-toolkit.readthedocs.io/en/latest/index.html

**Comment by mgrauer** [comment]
Does this issue point to automatically creating an API token that could be used in e.g. testing workflows, or should I open a separate issue for that?

**Comment by brianhelba** [comment]
@mgrauer I'm not clear on this question. Typically, API keys are used by machines to authenticate, in lieu of a username+password. I'm not sure whether we'd ever want API keys to be created normally, and testing workflows typically have driver scripts to handle that sort of setup.
