### ISSUE TITLE
Sync new dandisets from Girder

### ISSUE THREAD

**Issue by brianhelba** [dandi/dandi-publish#17]
When a new dandiset identifier is issued by Girder, it should be sync'd to the publish app.

The publish endpoint `POST /api/dandisets/sync/?folder-id=<girder_dandiset_folder_id>` (note the use of query string, not a form body) should be called to perform this sync. The endpoint will return a 202 ACCEPTED response, then will asynchronously (typically <5 seconds) update to recognize the new dandiset.

When this update completes, the new dandiset entry can be found at the `GET /api/dandisets/` endpoint and can be fetched in detail at the `GET /api/dandisets/<dandiset_identifier>` endpoint.

The `GET` endpoints do not require an authentication to call. However, requests to the `POST` endpoint must be authenticated via API key, as described by https://github.com/dandi/dandi-publish#api-authentication

**Comment by mgrauer** [comment]
Fixed by #46.
