### ISSUE TITLE
Publish new versions from Girder

### ISSUE THREAD

**Issue by brianhelba** [dandi/dandi-publish#21]
When a new dandiset version needs to be published, this should be done by the publish app, mediated by Girder.

The publish endpoint `POST /api/dandisets/<dandiset_identifier>/versions/publish` should be called to perform the publish. The endpoint will return a 202 ACCEPTED response, and will begin the publish process; this may take a long time to complete, and there is not currently a way to determine when it has finished.

The newly published version can be found at the `GET /api/dandisets/<dandiset_identifier>/versions/` endpoint, although the assets may not have completed publication when the version first appears here.

The `GET` endpoints do not require an authentication to call. However, requests to the `POST` endpoint must be authenticated via API key, as described by https://github.com/dandi/dandi-publish#api-authentication

**Comment by mgrauer** [comment]
I'll use this as a tracking issue ahead of going live with the publish service MVP.

- [ ] finish implementation here and in dandiarchive of locking #43 
- [ ] finish implementation here and in dandiarchive of sync #17 
- [ ] finish an MVP in dandiarchive of content browsing and merge into publish branch https://github.com/dandi/dandiarchive/pull/403
- [ ] point to S3 production bucket
- [ ] clean out django db
- [ ] merge the publish branch in dandiarchive https://github.com/dandi/dandiarchive/pull/341

**Comment by dchiquit** [comment]
Sync is finished on the publish branch, but contains backend code that is not merged into master, so it is not usable on the publish branch preview.

**Comment by mgrauer** [comment]
>Sync is finished on the publish branch, but contains backend code that is not merged into master, so it is not usable on the publish branch preview.

This is now out of date. The sync backend code has been merged and deployed to production Girder.
