### ISSUE TITLE
Track the internal status of the version publication process

### ISSUE THREAD

**Issue by brianhelba** [dandi/dandi-publish#22]
As new versions are created via publication, they should internally track whether they are pending or completed.

Until a version finishes publication, it should probably be excluded from the standard `/api/dandisets/<dandiset_identifier>/versions/` list. However, there should also be a mechanism to show pending versions, perhaps with more granular progress.

**Comment by mgrauer** [comment]
Would locking a publication-in-process be a part of this status tracking?

**Comment by mgrauer** [comment]
@dchiquit This might be a thing to include as part of implementing locking.
