### ISSUE TITLE
Add name and description to Version entity

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandi-publish#35]
Can two versions of the same dandiset have different names or descriptions?

**Comment by dchiquit** [comment]
I think it makes sense to have name/description tied to a specific version. I can imagine someone regretting their initial naming/description and requesting a change in Girder. At the same time we wouldn't want to modify a published dandiset, which is what would happen if name/description were tied to the dandiset object.

**Comment by mgrauer** [comment]
I don't see the name/description explicitly in the dandiset version. I assume it lives in the metadata. Shouldn't it exist more explicitly in columns?
