### ISSUE TITLE
List stats for dandisets

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandi-publish#36]
Include the number of assets and total number of bytes. Perhaps the total number of top level prefixes, but maybe that isn't a first pass.

This might be included as part of the dandiset details api or a separate endpoint, or maybe as an optional addition on the dandiset details.

**Comment by brianhelba** [comment]
@mgrauer Could you clarify which stats you want for a whole dandiset vs for a version within a dandiset?

**Comment by mgrauer** [comment]
These really would all be for a dandiset-version.
