### ISSUE TITLE
Create dandiset version DANDI schema formatted detail endpoint

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandi-publish#73]
Could be new endpoint or modification of existing endpoint.

[Relevant Code](https://github.com/satra/dandi-core/blob/4e35cf5c5dff6ca4672df1341a0e34a4f5e47450/scripts/models.py#L208-L216)

**Comment by mgrauer** [comment]
live at something like `dandiset/{dandiset_uuid}/version/{version}/manifest`
