### ISSUE TITLE
API /assets/: add an option to include metadata into the listing

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-publish#78]
For many use cases some metadata per each item out be desired in `dandi-cli`:
- for `ls` (not implemented yet): to list assets on remote end as it does locally
- for `download` (WiP): to obtain `uploaded_mtime` and `uploaded_nwb_object_id` (and possibly an extended list of digests) to make decision on either to download a newer version of the asset
- for `upload` (there is no API yet so we talk to girder directly ATM, but in the future): similar to `download` to make a decision either re-upload of the asset is needed

With current API it would mean an additional query per each asset to `/asset/{uuid}` end-point increasing the burden on the server and taking it longer overall. Adding some option like `include_metadata=true` into `/assets/` query would allow to avoid this additional interaction at a much smaller (IMHO) cost -- AFAIK metadata records are quite lean ATM and ok to be transferred... well, we could further improve it to make it actually into a `include_metadata=regex` instead of just a "bool".  That would allow clients to pick metadata to be transferred, thus decreasing the transfer burden etc (e.g. for upload/download could be `include_metadata=(uploaded_.*|md5)` or alike).

**Comment by brianhelba** [comment]
I agree. It's simpler to always include `metadata` in the asset listing endpoint.
