### ISSUE TITLE
API /assets/: why to include dandiset version record into each asset? 

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-publish#79]
ATM looks like
```
{
  "count": 53,
  "next": "http://publish.dandiarchive.org/api/dandisets/000006/versions/0.200714.1807/assets/?page=2",
  "previous": null,
  "results": [
    {
      "version": {
        "dandiset": {
          "identifier": "000006",
          "created": "2020-07-14T18:07:58.698604Z",
          "updated": "2020-07-14T18:07:58.698622Z"
        },
        "version": "0.200714.1807",
        "created": "2020-07-14T18:07:59.179296Z",
        "updated": "2020-07-14T18:07:59.179341Z"
      },
      "uuid": "846617c7-32f2-4dad-aa36-be03ba062e34",
      "path": "/sub-anm369962/sub-anm369962_ses-20170309.nwb",
      "size": 796920,
      "sha256": "8d1e87886816241d34c0ca248fc564d325c3aae1a35d0b22e01900ab1bd1a442",
      "created": "2020-07-14T18:07:59.710618Z",
      "updated": "2020-07-14T18:07:59.710660Z"
    },
    {
      "version": {
        "dandiset": {
          "identifier": "000006",
          "created": "2020-07-14T18:07:58.698604Z",
          "updated": "2020-07-14T18:07:58.698622Z"
        },
        "version": "0.200714.1807",
        "created": "2020-07-14T18:07:59.179296Z",
        "updated": "2020-07-14T18:07:59.179341Z"
      },
      "uuid": "6d78b6cf-f877-4953-aa39-b6233bd7ebab",
      "path": "/sub-anm369962/sub-anm369962_ses-20170310.nwb",
      "size": 6644036,
      "sha256": "d01c43576e3aeceed53a052defa8bbbf15b885146f518acf63d228cee44576ac",
      "created": "2020-07-14T18:08:00.634771Z",
      "updated": "2020-07-14T18:08:00.634816Z"
    },

```

note that there is 
```
      "version": {
        "dandiset": {
          "identifier": "000006",
          "created": "2020-07-14T18:07:58.698604Z",
          "updated": "2020-07-14T18:07:58.698622Z"
        },
        "version": "0.200714.1807",
        "created": "2020-07-14T18:07:59.179296Z",
        "updated": "2020-07-14T18:07:59.179341Z"
      },
```
in every asset record!
- "version" per se is not pertinent to an asset but to the dandiset 
- if desired (I can see how) to list dandiset a given asset belongs to, would be sufficient IMHO to just include record like
```
"dandiset": {
  "identifier": "000006",
  "version": "0.200714.1807"
}
```
and not to encumber it with all the time stamps and nested "version.version".

But also, looking forward to a "shared" (across versions? dandisets?) keystore, may be it is worth right away to provision it as a list:
```
"dandisets": [
 {
  "identifier": "000006",
  "version": "0.200714.1807"
 }
]
```
?

**Comment by brianhelba** [comment]
I agree, the name `version.version` is confusing. What would really help is a better domain-specific term for whatever is `"0.200714.1807"`.

We should not call it a "version", since "version" refers to the entire published entity. I suppose we could call it a "version_identifier", but we already have a totally distinct "identifier" field on Dandisets, and it seems a little verbose.

@yarikoptic Do you have any suggestions for what to call things like `"0.200714.1807"`?

**Comment by yarikoptic** [comment]
It is a version of the dandiset which contains this asset... asset doesn't have a version (neither a file in git per se, but git has no versions anyways -- just checksums + tags).
Since query is for a specific dandiset at a specific version, I do not think this information is really required to be returned for such a query -- requester knows for which dandiset at what version it was requested.
If you would like to list dandisets (versions) where such item could be found (including and besides the queried dandiset), then see an idea above with `"dandisets": [` entry

**Comment by mgrauer** [comment]
Maybe

```
"published_dandiset": {
    "dandiset": {
      "identifier": "000006",
      "created": "2020-07-14T18:07:58.698604Z",
      "updated": "2020-07-14T18:07:58.698622Z"
    },
    "version": "0.200714.1807",
    "created": "2020-07-14T18:07:59.179296Z",
    "updated": "2020-07-14T18:07:59.179341Z"
},
```

The reason to include this info is so that we have consistent responses for the same object types no matter where we are calling them from, and in addition the dandiset+version info rides along with the asset as the response is passed around so that it won't become decoupled. Clients that don't want to use this info can simply ignore it.

**Comment by yarikoptic** [comment]
For me, constancy with future draft API would be more important, so published_dataset is IMHO suboptimal
