### ISSUE TITLE
Reevaluate DB schema

### ISSUE THREAD

**Issue by dchiquit** [dandi/dandi-publish#9]
If we're going to go down the road of using `lookup_field = 'dandi_id'`, but `dandi_id` is not unique, then we probably should abandon the usage of `ModelViewSet`, as we're going to be fighting it far too much. However even if want to keep the exact same external API, we could consider refactoring the database to make a separate `DandisetVersion` model, which may significantly simplify the API implementation.

If we go that direction, we may want to use https://chibisov.github.io/drf-extensions/docs/#nested-routes to help structure the ViewSets.

_Originally posted by @brianhelba in https://github.com/dandi/dandi-publish/pull/7#issuecomment-630194632_

**Comment by brianhelba** [comment]
Completed.
