### ISSUE TITLE
API dandiset: why to nest dandiset metadata under "metadata.dandiset"?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-publish#99]
```shell
$> curl --silent -X GET "http://publish.dandiarchive.org/api/dandisets/000006/versions/0.200714.1807/" -H "accept: application/json" -H "X-CSRFToken: otOJPBXcQzTzzPs29GRQ5PvIui81aQXcZhha4QbKCW3SNX0mKKU2ctaKsjEsLhBi" | jq .
{
  "dandiset": {
    "identifier": "000006",
    "created": "2020-07-14T18:07:58.698604Z",
    "updated": "2020-07-14T18:07:58.698622Z"
  },
...
  "metadata": {
    "dandiset": {
      "sex": [
        "U"
...
```
so why to have that "dandiset" level under "metadata"?

**Comment by yarikoptic** [comment]
FTR: it is similar to what I get while traversing girder directly, i.e. it is just a matter of the fact that internally dandiset "metadata" record is stored under "dandiset" key within that girder folder metadata.  Although I see "implementation" rationale, as far as API goes, it is not clear why to have dandisets' metadata under "metadata.dandiset"

**Comment by brianhelba** [comment]
Anything currently within `metadata` is, from the perspective of the publish API, an unvalidated, unstructured blob, which we get directly from Girder. Of course, the validation should take place at least at the client level, so we do have some practical support for ensuring its correctness.

As we settle on a final set of schemas, we will be moving fields (speaking solely within the context of the publish API here) incrementally out of `metadata` and into strongly constrained top-level database fields. Eventually, the `metadata` field as a top-level entity should disappear entirely, as the metadata itself becomes the top-level content which the API serves and can be queried by.

We also plan to provide dedicated endpoints to return metadata which is structured in the canonical "DANDI format" (i.e. YAML-encoded, JSON-LD scheme).

**Comment by brianhelba** [comment]
I'm going to close this issue, since it's not directly actionable. The metadata content migration plan is tracked as a higher level effort. Feel free to respond or reopen if there's any follow-up.

**Comment by mgrauer** [comment]
There were three issues for the canonical "DANDI format" endpoints, but their naming wasn't clear. I've edited the issue titles.

#72, #73, #74
